name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

# thanks https://github.com/dixyes/ghactionsplay/blob/main/.github/workflows/glibc217node20.yml

jobs:
  ubuntu_24_cuda:
    name: Ubuntu 24 CUDA
    runs-on: [self-hosted, Linux, X64, cuda]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: torch
      run: scripts/install-torch2.sh
    - name: build cuda=1
      run: make cuda=1 CUDA_ARCH=-arch=sm_50
    - name: test
      run: export DEVICE=cuda:0 && make test